Python 3.3.0 (v3.3.0:bd8afb90ebf2, Sep 29 2012, 10:55:48) [MSC v.1600 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
>>> run_tests()
Trying:
    roll_double(2, 5)
Expecting:
    7
**********************************************************************
File "C:\Python33\Homework\p02.1-master\p02.1-master\roll_doubles.py", line 14, in __main__
Failed example:
    roll_double(2, 5)
Expected:
    7
Got:
    result
Trying:
    roll_double(4, 5)
Expecting:
    9
**********************************************************************
File "C:\Python33\Homework\p02.1-master\p02.1-master\roll_doubles.py", line 16, in __main__
Failed example:
    roll_double(4, 5)
Expected:
    9
Got:
    result
Trying:
    roll_double(2, 2)
Expecting:
    8
**********************************************************************
File "C:\Python33\Homework\p02.1-master\p02.1-master\roll_doubles.py", line 18, in __main__
Failed example:
    roll_double(2, 2)
Expected:
    8
Got:
    result
Trying:
    roll_double(5, 5)
Expecting:
    20
**********************************************************************
File "C:\Python33\Homework\p02.1-master\p02.1-master\roll_doubles.py", line 20, in __main__
Failed example:
    roll_double(5, 5)
Expected:
    20
Got:
    result
2 items had no tests:
    __main__.roll_double
    __main__.run_tests
**********************************************************************
1 items had failures:
   4 of   4 in __main__
4 tests in 3 items.
0 passed and 4 failed.
***Test Failed*** 4 failures.
>>> ================================ RESTART ================================
>>> 
>>> run_tests()
Trying:
    roll_double(2, 5)
Expecting:
    7
ok
Trying:
    roll_double(4, 5)
Expecting:
    9
ok
Trying:
    roll_double(2, 2)
Expecting:
    8
ok
Trying:
    roll_double(5, 5)
Expecting:
    20
ok
2 items had no tests:
    __main__.roll_double
    __main__.run_tests
1 items passed all tests:
   4 tests in __main__
4 tests in 3 items.
4 passed and 0 failed.
Test passed.
>>> 
